Add PID coefficients for elbow and shoulder motors
huskyroboticsteam/PY2020 pull request #103
Opened 2021-05-21 04:21 UTC by nhatch

We have PID control working for these two motors! The fixes were some firmware tweaks and a couple of software-side changes (such as making sure we only send the mode set packet once).

Tracking for the TunePID script has an RMSE of about 4 degrees for the shoulder and about 2 degrees for the elbow. (This is just tracking latency; there's no steady-state error.) We might be able to improve this later, but it's good enough for now.

2021-05-21 17:08 UTC, evan3334 requested changes
Looks good to me; I just had one comment on the arrays of PID coefficients. We probably ought to use regular arrays instead of C++ vectors unless we really need them to be vectors.

2021-05-21 17:16 UTC, evan3334 commented on src/Rover.cpp
> +const std::vector<uint8_t> arm_encoder_signs = {
```suggestion
constexpr int32_t arm_Ps[] = {
   0,    100,    500,     0,       0,         0
};
constexpr int32_t arm_Is[] = {
   0,      0,    300,     0,       0,         0
};
constexpr int32_t arm_Ds[] = {
   0,   1000,  10000,     0,       0,         0
};
constexpr uint8_t arm_encoder_signs[] = {
```

2021-05-21 23:45 UTC, Jacob6819 commented
I've read over all of the changed files and they look good to me.

2021-05-22 01:17 UTC, evan3334 approved these changes

2021-05-22 01:18 UTC, merged