Implement autonomous leg sequencing
huskyroboticsteam/PY2020 pull request #114
Opened 2021-06-04 04:10 UTC by arnavthareja

This PR implements sequencing multiple autonomous legs. When the rover completes a leg, it will start the next leg once the enter key has been pressed in the terminal. This works well in the simulator, but we may want to send this as a command from the base station when used on the real rover.

This also implements parsing autonomous legs from GPS coordinates in a well-formatted file. The filepath can be changed in `Rover.cpp`. If no file is given or the file doesn't exist or contains no valid legs, the default simulator legs are used.

There are also some small refactors included.

2021-06-04 17:24 UTC, nhatch requested changes
Nice work!

I have a few specific suggestions. I also realize belatedly that it's a bit weird having the `gpsToMeters` thing in a file that's only included on the real rover, so I'll push a quick fix for that to this PR.

2021-06-04 17:24 UTC, nhatch commented on src/Autonomous.cpp
> +		log(LOG_INFO, "Cannot start next leg: current leg not done\n");
Since this is an unexpected case, this should probably be `LOG_WARN` instead of just `LOG_INFO`.

2021-06-04 17:24 UTC, nhatch commented on src/Autonomous.cpp
> +		rightPostFilter.reset();
As discussed below, let's remove the `currentLegDone()` method and move these three statements to the `startNextLeg()` method. Then I think we can get rid of this block of code completely, which simplifies things.

2021-06-04 17:24 UTC, nhatch commented on src/Rover.cpp
> +
As discussed above, I think we can avoid all of this code (lines 205-222) using the new `{"type":"autonomous"}` message from the base station. It's better not to block in the main control loop, anyway.

2021-06-04 18:41 UTC, evan3334 approved these changes
Nathan seems to have covered most of the minor bugs and organization issues, so I'm just going to approve. Aside from those issues, it looks good to me! I noticed that the result of `_targets.front()` is used directly in a lot of places so I was going to ask about the possibility of it being empty, but it seems like the invariant that the queue is not empty when these accesses happen is pretty reasonably enforced.

2021-06-04 18:55 UTC, nhatch commented on src/CMakeLists.txt
> +target_link_libraries(rover_common gps)
Fixed.

2021-06-05 03:11 UTC, arnavthareja commented
Made the requested changes. I'm running into a new problem while testing where the rover almost always thinks a collision is imminent (I suspect this is related to planning or the recent simulator realism updates). When I test the changes with the collision stopping commented out, everything works as expected.

2021-06-05 03:50 UTC, nhatch approved these changes
Looks great!

2021-06-05 03:50 UTC, nhatch commented on src/example_gps_legs.txt
> +5 -1 47.653525 -123.305486
Nice, I like the demos of all the different valid syntax

2021-06-05 03:50 UTC, merged