Add code to ping motors on startup
huskyroboticsteam/PY2020 pull request #346
Opened 2024-11-22 02:37 UTC by abnv-goyal

2025-01-19 00:49 UTC, huttongrabiel requested changes
This is a good start! I think we need to talk about if this is the right location for this function and then also implement calling it on start. Nice work!

2025-01-19 00:49 UTC, huttongrabiel commented on src/control_interface.cpp
> +		can::pullDeviceTelemetry(std::make_pair(can::devicegroup_t::motor, motorMap.second),
You do `std::make_pair(can::devicegroup_t::motor, motorMap.second)` twice. Can you pull it out into a variable at the top and then pass it in?

2025-01-19 00:49 UTC, huttongrabiel commented on src/control_interface.cpp
> +		if (!hasData(std::make_pair(can::devicegroup_t::motor, motorMap.second))) {
Second time doing `std::make_pair(can::devicegroup_t::motor, motorMap.second)` is here

2025-02-04 02:22 UTC, huttongrabiel reviewed
nice!

take a look at rover.cpp and i think you can call this function in the start() function in there and it will ensure everything it set up correctly.

2025-02-04 02:23 UTC, huttongrabiel commented
also merge master into this branch so youre up to date

2025-02-26 19:26 UTC, imisaacwu commented on src/CAN/CANUtils.cpp
> +			throw std::runtime_error("Not all motors connected!");
You could consider removing just this line for the function to go through all the pairs & not throw an error, but it's up to you how you want to implement it. We just want to be able to run this function and see a list of errors with the motors that aren't connected. It may also be nice to do an info log with "Motors are all connected!" if they are all connected

2025-03-01 20:02 UTC, imisaacwu submitted a review, later dismissed
lgtm, just needs testing!

2026-08-12 20:51 UTC, closed without merging